database:
  host: db
  port: "5432"
  user: root
  password: root
  databaseName: spooky_bodies
TokenLifeSpan: 15
JWTKey: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDAwNzYwNjcsIm9yaWdfaWF0IjoxNzAwMDcyNDY3LCJ1c2
Environment: develop