services:

  spooky-server:
    image: lyred/spooky-server:v0.1.0
    volumes:
      - "./config.yaml:/opt/spooky-server/config.yaml:ro"
    command: "go run ./cmd"
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "spooky_bodies"
    restart: always
    volumes:
      - "db_data:/var/lib/postgresql/data"

  adminer:
    image: adminer
    restart: always
    ports:
      - "9000:8080"
    depends_on:
      - db

volumes:
  db_data:
