services:

  spooky-server:
    image: lyred/spooky-server
    volumes:
      - "./:/app:ro"
      - "server_go_data:/go"
    working_dir: "/app"
    command: "go run ./cmd"
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "spooky_bodies"
    restart: always
    volumes:
      - "db_data:/var/lib/postgresql/data"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
  server_go_data:
